name: Bond_Notifier
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  easy_localization: ^3.0.3
  connectivity_plus: ^6.0.3
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  http: ^1.2.1
  dio: ^5.7.0
  shared_preferences: ^2.2.3
  path_provider: ^2.1.2
  path: ^1.8.3
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  animate_do: ^3.0.2

  flutter_localizations:

    sdk: flutter
  logger: ^2.2.0
  flutter_dotenv: ^6.0.0
  get: ^4.6.6
  image_picker: ^1.1.0
  internet_connection_checker_plus: ^2.3.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/flag_uk.png
    - assets/icons/flag_bd.png
    - assets/icons/google.png
    - assets/icons/logo.png