name: bond_notifier_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  easy_localization: ^3.0.3
  connectivity_plus: ^6.0.3
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  http: ^1.2.1
  dio: ^5.7.0
  shared_preferences: ^2.2.3
  path_provider: ^2.1.2
  path: ^1.8.3
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  animate_do: ^3.0.2

  flutter_localizations:

    sdk: flutter
  logger: ^2.2.0
  flutter_dotenv: ^6.0.0
  get: ^4.6.6
  image_picker: ^1.1.0
  internet_connection_checker_plus: ^2.3.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/flag_uk.png
    - assets/icons/flag_bd.png
    - assets/icons/google.png
    - assets/icons/logo.png